# Generated by Django 5.1.4 on 2024-12-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='signup',
            new_name='signup_id',
        ),
    ]
