# Generated by Django 5.1.4 on 2024-12-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0002_rename_signup_register_signup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='signup_id',
        ),
    ]
