# Generated by Django 5.1.4 on 2024-12-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0003_remove_register_signup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewWeb',
            fields=[
                ('revWeb_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('review_field', models.TextField()),
            ],
        ),
    ]
