# Generated by Django 5.1.4 on 2024-12-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0004_reviewweb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewweb',
            old_name='revWeb_id',
            new_name='revweb_id',
        ),
    ]
