# Generated by Django 5.1.4 on 2024-12-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0005_rename_revweb_id_reviewweb_revweb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewweb',
            old_name='revweb_id',
            new_name='revw_id',
        ),
    ]
