# Generated by Django 5.1.4 on 2024-12-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0006_rename_revweb_id_reviewweb_revw_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
