# Generated by Django 5.1.4 on 2024-12-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0008_rename_account_field_register_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='signup_id',
            new_name='signup',
        ),
    ]
