# Generated by Django 5.1.4 on 2024-12-15 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0014_remove_register_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Profile',
        ),
    ]
