# Generated by Django 5.1.4 on 2024-12-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0018_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='listbook',
            fields=[
                ('book_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=150)),
                ('number_of_pages', models.IntegerField()),
                ('years', models.PositiveBigIntegerField()),
                ('synopsis', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_image', models.ImageField(upload_to='cover/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraria.category')),
            ],
        ),
    ]
