# Generated by Django 5.1.4 on 2024-12-16 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0020_listbook_librender_listbook_stok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='review_book',
            fields=[
                ('reviewbook_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('booktitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraria.listbook')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
