# Generated by Django 5.1.4 on 2024-12-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0021_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listbook',
            name='librender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraria.profile'),
        ),
    ]
