# Generated by Django 5.1.4 on 2024-12-16 11:31

import libraria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0024_borrowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateField(default=libraria.models.default_return_date),
        ),
    ]
