# Generated by Django 5.1.4 on 2024-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraria', '0025_alter_borrowing_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='denda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='status',
            field=models.CharField(default='Borrowed', max_length=20),
        ),
    ]
